module.exports = {
  SECRET: 'ANANYA-SECRET-KEY',
  ADMIN_FULLNAME: 'ADMIN',
  ADMIN_EMAIL: 'ADMIN@GMAIL.COM',
  ADMIN_PASSWORD: 'ADMIN123',
  ALGORITHM: 'HS256',
  EXPIRES_IN: 2592000,
  LOGIN_TOKEN_TYPE: 'LOGIN',
  RESET_TOKEN_TYPE: 'RESET_PASSWORD',
  FORGOT_TOKEN_TYPE: 'FORGET_PASSWORD',
  ADMIN_TYPE: 'ADMIN',
  USER_TYPE: 'USER',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  PENDING: 'PENDING',
  DELETED: 'DELETED'
};
